//
//  ListUserGithubModels.swift
//  Github Fetch Data
//
//  Created by daniel on 14/04/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListUserGithub
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum FetchUser
    {
        struct Request
        {
            
        }
        struct Response
        {
            var users : [Users]
        }
        struct ViewModel
        {
            var displayUsers: [Users]
        }
    }
}
