//
//  ListUserGithubInteractor.swift
//  Github Fetch Data
//
//  Created by daniel on 14/04/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUserGithubBusinessLogic
{
    func fetchUser(request: ListUserGithub.FetchUser.Request)
}

protocol ListUserGithubDataStore
{
    //var name: String { get set }
}

class ListUserGithubInteractor: ListUserGithubBusinessLogic, ListUserGithubDataStore
{
    
    
    var presenter: ListUserGithubPresentationLogic?
    var worker = ListUserGithubWorker()
    //var name: String = ""
    
    // MARK: FETCH USER
    
    func fetchUser(request: ListUserGithub.FetchUser.Request) {
        
        self.worker.fetchUsers(request: request){ (res) -> Void in
            let response = ListUserGithub.FetchUser.Response(users:res)
            self.presenter?.presentUsers(response: response)
        }
    }
}
