//
//  ListUserGithubPresenter.swift
//  Github Fetch Data
//
//  Created by daniel on 14/04/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUserGithubPresentationLogic
{
    func presentSomething(response: ListUserGithub.Something.Response)
    
    func presentUsers(response: ListUserGithub.FetchUser.Response)
}

class ListUserGithubPresenter: ListUserGithubPresentationLogic
{
    weak var viewController: ListUserGithubDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ListUserGithub.Something.Response)
    {
        let viewModel = ListUserGithub.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentUsers(response: ListUserGithub.FetchUser.Response) {
        let viewModel = ListUserGithub.FetchUser.ViewModel(displayUsers: response.users)
        viewController?.displayUsers(viewModel:viewModel)
    }
}
