//
//  ListUserGithubWorker.swift
//  Github Fetch Data
//
//  Created by daniel on 14/04/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class ListUserGithubWorker 
{
    
    func fetchUsers(request: ListUserGithub.FetchUser.Request,completionHandler: @escaping (_ users: [Users]) -> Void)
    {
        UserAPI.fetchUser{ (users) -> Void in
            
            completionHandler(users)
            
        }
    }
    
}
